### ISSUE TITLE
Named capturing matchers

### ISSUE THREAD

**Issue by netthier** [dadrus/heimdall#1038]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I have discussed this feature request with the community.

### Describe the background of your feature request

Authorizing based on path components is currently a bit hacky. 
If I have an API like `/file/<uuid>/delete` I need to both match the `<uuid>` part exactly and then again retrieve it inside of the authorizer by extracting it out of `.Request.URL.Path`. This kind of double matching is in my opinion error-prone, and retrieving path segments from the full path via regular expressions or numeric indexing is not very readable, especially if the template is defined separately from the rule.

### Describe your idea

I propose an additional kind of matcher, which would always be named and equivalent to the `<*>` glob (though to be useful https://github.com/dadrus/heimdall/issues/1037 needs to be implemented in some capacity).
This matcher would be trivially convertable to regexp, where named capturing shouldn't be an issue (unlike with the current glob library).
Compare
```yaml
rules:
  - id: rule:1
    match:
      url: http://hosty.mchostface/files/<*>/delete
    forward_to:
      host: server:8080
    methods:
      - ALL
    execute:
      - authorizer: openfga_check # remote authorizer 
        config:
          # Note: I originally wanted to do this with values, but apparently they cannot template? They should be able to :v
          payload: |
            {
              "user": {{ .Subject.ID | quote }},
              "relation": "can_delete",
              "object": "file:{{ index (splitList "/" .Request.URL.Path) 2 }}"
            }
```
and
```yaml
rules:
  - id: rule:1
    match:
      url: http://hosty.mchostface/files/<:uuid>/delete
    forward_to:
      host: server:8080
    methods:
      - ALL
    execute:
      - authorizer: openfga_check # remote authorizer 
        config:
          payload: |
            {
              "user": {{ .Subject.ID | quote }},
              "relation": "can_delete",
              "object": "file:{{ .Request.URL.Captures.uuid }}"
            }
```

### Are there any workarounds or alternatives?

See the first example above

### Version

dev (cda0a84)

### Additional Context

Originally suggested on Discord here: https://discord.com/channels/1100447190796742698/1174322443859538000/1174322443859538000
