### ISSUE TITLE
Allow templating in authorizer/contextualizer values

### ISSUE THREAD

**Issue by netthier** [dadrus/heimdall#1039]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I have discussed this feature request with the community.

### Describe the background of your feature request

Given an authorizer connected to a service such as OpenFGA, I'm not able to make checks based on dynamic data without overriding the payload, e.g.
```yaml
      - authorizer: openfga_check
        config:
          payload: |
            {
              "user": "user:{{ .Subject.ID }}",
              "relation": "can_delete",
              "object": "file:{{ .Request.URL.Captures.uuid }}"
            }
```

### Describe your idea

Instead, I want to be able to define the authorizer as
```yaml
      - id: openfga_check
        type: remote
        config:
          endpoint:
            url: https://openfga.local
          payload: |
            {
              "user": {{ .Values.user | quote }},
              "relation": {{ .Values.relation | quote }},
              "object": {{ .Values.object | quote }}
            }
```
and then call it like
```yaml
  - authorizer: openfga_check
    config:
      values:
        user: "{{ .Subject.ID }}"
        relation: can_delete
        object: "{{ .Request.Path.Captures.uuid }}"
```

Same should apply for all other mechanisms offering a `values` configuration.
### Are there any workarounds or alternatives?

See payload-overriding variant above

### Version

dev (cda0a84)

### Additional Context

This feature request was discussed on Discord: https://discord.com/channels/1100447190796742698/1174345483683123211
