### ISSUE TITLE
Align the conditional statements for regular and the error pipeline

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#1048]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I have discussed this feature request with the community.

### Describe the background of your feature request

As of today, the regular pipeline (execute) allows conditional execution of mechanisms using an if clause expecting a CEL expression (with access to Subject and the Request objects)
The error pipeline (on_error) has a similar construct but on the config level of the error handlers - namely the where clause.

### Describe your idea

I propose to align the conditional execution of mechanisms and drop the `where` clause from the configuration of the error handlers and allow usage of the `if` clause instead. That way, there will be no difference in the configuration of the respective pipelines. In addition to the `Subject` and the `Request` objects, the `if` clause in the error pipeline would have access to an `Error` object. 

This new `Error` object would offer two properties:
* `chain`, which is basically a "stack trace" as an array of error types
* `raisedBy`, which provides the id of the mechanism, which raised that error

With that in place one can check whether the raised error is of a specific type by e.g. `"authentication_error" in Error.chain`  and with e.g. `Error.raisedBy == "basic_auth_authenticator"` one can check whether an error has been raised by a mechanism with a particular id. 

So the following error pipeline definition
```yaml
error_handlers:
- id: basic_authenticate
  type: www_authenticate
  config:
    realm: "My fancy app"
    when:
      - error:
        - type: authentication_error
          raised_by: basic_auth_authenticator
        request_headers:
          Accept:
            - text/html
```
would become
```yaml
error_handlers:
- id: basic_authenticate
  type: www_authenticate
  config:
    realm: "My fancy app"
  if: |
    "authentication_error" in Error.chain &&
    Error.raisedBy == "basic_auth_authenticator" &&
    Request.Header("Accept") == text/html
```

### Are there any workarounds or alternatives?

Beyond the verbosity and comprehension limitations of the current approach is fine

### Version

v0.11.1-alpha

### Additional Context

This FR is discussed in Discord here: https://discord.com/channels/1100447190796742698/1176148154496856064/1176148154496856064
