### ISSUE TITLE
Rules from different rule sets but with same rule id interfere with each other on update or deletion

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#1297]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Describe the bug

If there are multiple rule sets with rules having the same IDs, deletion one rule set will also unload rules with the same id loaded from other rule sets. Same interference is also present if a rule set is updated. Rules with the same id loaded from other rule sets will be overwritten with rules coming from the updated rule set.

### How can the bug be reproduced

1. Create a configuration file (`config.yaml`) for heimdall with the following contents:
    ```yaml
    log:
      level: debug

    mechanisms:
      authenticators:
        - id: anon
          type: anonymous
      finalizers:
        - id: create_jwt
          type: jwt

    providers:
      file_system:
        src: ./rules
        watch: true
    ```
2. Create a directory named `rules` in the same directory in which the configuration file from step 1 has been created
3. Create a rule set file named `rule-set-1.yaml` with the following contents in the `rules` directory :
    ```yaml
    version: "1alpha3"
    rules:
      - id: test
        match:
          url: http://<**>/foo
        methods:
          - ALL
        execute:
          - authenticator: anon
          - finalizer: create_jwt
    ```
4. Start heimdall with `./heimdall -c config.yaml serve decision`
5. Call heimdall's decision endpoint with `curl -v http://127.0.0.1:4456/foo`. You should see an HTTP `200 OK` response with a JWT created by heimdall.
6. Create a copy of the `rule-set-1.yaml` file in the `rules` directory (name that new file as you want) and delete it.
7. Call heimdall's decision endpoint with `curl -v http://127.0.0.1:4456/foo`. You should see an HTTP `404 Not Found` response.

The above steps demonstrate the deletion issue. Based on the above configuration one can also reproduce the update issue. To achieve that, update the copy of the rule set created in the step 6 instead of deleting it as shown below:

```yaml
version: "1alpha3"
rules:
  - id: test
    match:
      # change the url path to end with bar
      url: http://<**>/bar
    methods:
      - ALL
    execute:
      - authenticator: anon
      # remove the finalizer
```

If you now call the `curl -v http://127.0.0.1:4456/foo`, you'll see an HTTP `404 Not Found` again.

### Relevant log output

```shell
2024-04-01T14:27:49+02:00 DBG Rule update event received _event="REMOVE        \"/tmp/rules/rule-set-2.yaml\"" _provider_type=file_system _src=/tmp/rules/rule-set-2.yaml
2024-04-01T14:27:49+02:00 INF Rule set changed _src=file_system:/tmp/rules/rule-set-2.yaml _type=Remove
2024-04-01T14:27:49+02:00 INF Deleting rule set _src=file_system:/tmp/rules/rule-set-2.yaml
2024-04-01T14:27:49+02:00 DBG Rule removed _id=test _src=file_system:/tmp/rules/rule-set-1.yaml
2024-04-01T14:27:49+02:00 DBG Rule removed _id=test _src=file_system:/tmp/rules/rule-set-2.yaml
```

As you can see in the log output above, deletion of the `rule-set-2.yaml` leads also to the deletion of the `test` rule from loaded from the `rule-set-1.yaml` file.

### Relevant configuration

See above

### Version

v0.13.0-alpha

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

None

### Additional Context

This issue prevents development of rules if heimdall is running in docker with the `file_system` provider configured to watch the directory with rules as a temporary file ending with `~` is created first and then deleted after the actual rule set file is added to the directory.
