### ISSUE TITLE
Heimdall freezes while loading of PEM files with trailing new lines 

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#1562]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Describe the bug

When heimdall is configured to use a PEM file, e.g. for TLS configuration or for JWT signer configuration, and that file contains trailing new lines, or any garbage after the last entry, the process freezes in an endless loop.

### How can the bug be reproduced

1. Generate a key pair e.g. using openssl: `openssl ecparam -name secp256k1 -genkey -noout -out signer.pem`
2. Open the created `signer.pem` file in an editor of your choice and add some trailing lines to the end of it. Save.
3. Create a config file (see below) for heimdall and configure the `signer` property to use the `signer.pem` file created in step 1
4. Start heimdall by referencing the config file from step 3

The process will freeze before starting any of the available services.

### Relevant configuration

```yml
log:
  level: debug

signer:
  key_store:
    path: signer.pem

mechanisms:
  authenticators:
    - id: anon
      type: anonymous
  finalizers:
    - id: jwt
      type: jwt
```

### Version

v0.14.3-alpha

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

### Additional Context

The workaround is to remove all empty lines, respectively useless content after the last entry in the PEM file
