### ISSUE TITLE
Varification of the OAuth2 `iss` claim fails in JWT authenticators when used with `metadata_endpoint`

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#1659]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Describe the bug

The issue has been encountered with `jwt` authenticator used to verify the authentication status of requests against different Keycloak realms. Important to note is that the first request succeeds, but all subsequent requests fail as soon the token to be verified has been issued by a realm different from the one, which issued the token of the above said initial request.

It looks like the first response from the `metadata_endpoint` is cached and is used instead of the new ones.

### How can the bug be reproduced

1. Configure Keycloak to have two realms and two users, each in a different realm
2. Configure an OIDC client in Keycloak
3. Configure heimdall with a `jwt` authenticator, which makes use of that client to communicate to Keycloak and does it over the OIDC dicovery endpoint (by making use of the `metadata_endpoint` property)
4. Let Keycloak issue an access token for each of the users in JWT format
5. Let heimdall verify these tokens by sending corresponding requests to it. It will fail with the error message shown below, even the 

### Relevant log output

```shell
2024-07-24T19:43:28+01:00 ERR Pipeline step execution failed error="authentication error: access token does not satisfy assertion conditions: assertion error: issuer http://localhost:8080/realms/second is not trusted"
```

### Relevant configuration

```yml
mechanisms:
  authenticators:
    - id: keycloak
      type: jwt
      config:
        metadata_endpoint: https://localhost:8080/realms/{{ trimPrefix "https://localhost:8080/realms/" .TokenIssuer }}/.well-known/openid-configuration
        assertions:
          allowed_algorithms:
            - RS256
  finalizers:
    - id: noop
      type: noop

default_rule:
  execute:
    - authenticator: keycloak
    - finalizer: noop
```

### Version

v0.14.3-alpha

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Binary
