### ISSUE TITLE
Support for OAuth2-Proxy Cookie Splitting

### ISSUE THREAD

**Issue by aslafy-z** [dadrus/heimdall#2204]
### Preflight checklist

- [x] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [x] I have discussed this feature request with the community.

### Describe the background of your feature request

OAuth2-Proxy uses cookie splitting when session cookies exceed a certain size, breaking the authentication workflow in Heimdall.  

Given a OAuth2-Proxy configured with `cookie-name: SESSION`:
When the session cookie is small (<4KB), it is stored under the name `SESSION`.  
When it exceeds the limit, it is split into multiple parts: `SESSION_0`, `SESSION_1`, `SESSION_N`.  

Currently, Heimdall does not provide a way to handle this dynamically, leading to failures in both cases:  

- If no cookie splitting occurs (`SESSION` is used), configurations listing `SESSION_0` or `SESSION_1` fail because they do not exist.  
- If cookie splitting occurs (`SESSION` is absent, but `SESSION_0`, `SESSION_1`, etc., are present), Heimdall fails to locate the expected cookie.  

Example configuration:  

```yaml
- id: auth
  type: generic
  config:
    identity_info_endpoint: http://oauth2-proxy:4180/oauth2/userinfo
    authentication_data_source:
      - cookie: SESSION
    forward_cookies:
      - SESSION
    subject:
      id: "user"
```
  
This works when `SESSION` is available but fails when splitting occurs. If we attempt to list multiple cookies, the opposite problem occurs:  

```yaml
- id: auth
  type: generic
  config:
    identity_info_endpoint: http://oauth2-proxy:4180/oauth2/userinfo
    authentication_data_source:
      - cookie: SESSION
      - cookie: SESSION_0
      - cookie: SESSION_1
    forward_cookies:
      - SESSION
      - SESSION_0
      - SESSION_1
    subject:
      id: "user"
```
  
Here, if no splitting happens, `SESSION_0` and `SESSION_1` do not exist, breaking the workflow.  

### Describe your idea

A mechanism to handle cookie splitting dynamically would be beneficial. Possible approaches include:  

1. **OR-based selection**  
   - Allow authentication using either `SESSION` or the combination of `SESSION_0`, `SESSION_1`, etc.  
   - This does not natively handles situations where cookies are split into more than two parts.

2. **Optional cookies**  
   - Allow defining optional cookies (e.g., `SESSION`, `SESSION_0`, `SESSION_1`) without failing if some are missing.  
   - Downside: No validation of expected cookies.  

3. **Prefix-based matching**  
   - Support wildcard or prefix matching (e.g., `SESSION*` or `SESSION_*`).  
   - Ideally combined with OR logic: `SESSION or SESSION_*`.  

4. **Regex-based selection**  
   - Allow defining authentication cookie sources with a pattern such as `SESSION(?:_[0-9]+)?`.  
   - More flexible and scalable than listing cookies explicitly.  

**Considerations:**  
- The `forward_cookies` interface currently supports a static list, making dynamic selection challenging. Some rework would be needed to support this feature.  

### Are there any workarounds or alternatives?

A partial workaround exists: configuring **session-cookie-minimal** mode in OAuth2-Proxy (https://github.com/oauth2-proxy/oauth2-proxy/pull/673).  
- This significantly reduces cookie size, avoiding splitting.  
- However, it removes token information, making tokens unavailable to downstream applications.  

### Version

v0.15.6

### Additional Context

Before implementing a complex solution in Heimdall, it is worth considering the discussion in https://github.com/oauth2-proxy/oauth2-proxy/issues/482, which suggest transitioning to server-side session storage solutions, such as Memory, Redis, to manage larger sessions more effectively and eliminate the need for cookie splitting.
