### ISSUE TITLE
multiple hosts support

### ISSUE THREAD

**Issue by albertilagan** [dadrus/heimdall#2232]
### Preflight checklist

- [x] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [x] I could not find a solution in the existing issues, docs, nor discussions.

### Describe the bug

When doing a matcher on multiple host it doesn't seem to work.

```
  - id: routes:protected
    match:
      scheme: http
      hosts:
        - type: exact
          value: service-1.myapp.test
        - type: exact
          value: service-2.myapp.test
      routes:
        - path: /**
    execute:
      - authenticator: kratos_session
      - authorizer: allow
      - finalizer: create_jwt
      - finalizer: add_kratos_session_to_header
```

### How can the bug be reproduced

1. serve heimdall with traefik
2. call endpoint

### Relevant log output

```shell
2025-02-26T17:53:02+08:00 INF TX started _client_ip=127.0.0.1 _http_host=0.0.0.0:4456 _http_method=GET _http_path=/ _http_scheme=http _http_user_agent=connect-es/2.0.1 _http_x_forwarded_for=127.0.0.1 _http_x_forwarded_host=identity.tenki.lab:80 _http_x_forwarded_method=POST _http_x_forwarded_proto=http _http_x_forwarded_uri=/tenki.cloud.identity.v1beta1.IdentityService/GetUser _tx_start=1740563582
2025-02-26T17:53:02+08:00 INF Executing default rule
2025-02-26T17:53:02+08:00 INF Pipeline step execution failed error="authentication error: denied by authenticator"
2025-02-26T17:53:02+08:00 WRN No applicable error handler found
```

### Relevant configuration

```yml
version: "1alpha4"
rules:
  - id: routes:protected
    match:
      scheme: http
      hosts:
        - type: exact
          value: engine.myapp.test
        - type: exact
          value: identity.myapp.test
      routes:
        - path: /**
    execute:
      - authenticator: kratos_session
      - authorizer: allow
      - finalizer: create_jwt
      - finalizer: add_kratos_session_to_header
```

### Version

v0.15.7

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

None

**Comment by dadrus** [comment]
Until the fix for this issue is released, the workaround is to use a single `host` expression based on glob or regex. For the example provided in the bug description, it would look as shown below if glob is used as type.

```yaml
hosts:
  - type: glob
    value: {engine.myapp.test,identity.myapp.test}
```
