### ISSUE TITLE
Heimdall overwrites multiple header values for the same header when using multiple header finalizers

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#2237]
### Preflight checklist

- [x] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [x] I could not find a solution in the existing issues, docs, nor discussions.

### Describe the bug

When attempting to set the same header multiple times with different values using multiple header finalizers, heimdall overwrites the previous value of the header, instead of setting it as a separate value. This issue prevents the use of the same header with different values, which is required in cases like Kubernetes impersonation mode for the `Impersonation-Group` header. The overwriting behavior was implemented to prevent header spoofing, but it is definitely not desirable in decision mode, where no spoofing can occur. It is also not desirable in proxy mode, at least as it is implemented today. In proxy mode, heimdall should drop any existing headers with the same name before setting the new value to prevent spoofing, while still allowing multiple values to be set for the same header. Otherwise, even if the FR in #2206 is implemented, it won't function as expected. Addressing this issue would also serve as a workaround until the referenced FR is implemented.

### How can the bug be reproduced

1. If the mechanism catalog of Heimdall contains the following header finalizer definition:
    ```yaml
    mechanisms:
      finalizers:
        - id: set_header
          type: header
          config:
            headers:
              Impersonation-Group: SomeValue
    ```

2. And the rule contains the following entries in its pipeline:
    ```yaml
    execute:
      - finalizer: set_header
        config:
          headers:
            Impersonation-Group: Group1
      - finalizer: set_header
        config:
          headers:
            Impersonation-Group: Group2
    ```
3. The forwarded request, or the response to the proxy integrating with heimdall, will only contain the header `Impersonation-Group: Group2`, and not `Impersonation-Group: Group1` which is however the exepected behavior.

### Relevant log output

```shell

```

### Relevant configuration

```yml

```

### Version

0.15.7

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker
