### ISSUE TITLE
Condition Message / Error Message length limited to 1024 chars

### ISSUE THREAD

**Issue by flosk8** [dadrus/heimdall#2514]
### Preflight checklist

- [x] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [x] I could not find a solution in the existing issues, docs, nor discussions.

### Describe the bug

I had an semanical error in a cel Authorizer in RuleSet on gke:

```yaml
         - authorizer: allow_by_ip
          config:
            expressions:
              - expression: |
                  Request.ClientIPAddresses[0] in networks("10.0.0.0/8","192.163.1.0/19")
```

The error message could not be logged because it was longer than 1024 characters.

should be (symantical correct in [ ]):
```yaml
        - authorizer: allow_by_ip
          config:
            expressions:
              - expression: |
                  Request.ClientIPAddresses[0] in networks(["10.0.0.0/8","192.163.1.0/19"])
```

### How can the bug be reproduced

See description

### Relevant log output

```shell
"your-rule-set\" is invalid: [status.conditions[0].message: Too long: may not be longer than 1024
```

### Relevant configuration

```yml

```

### Version

0.15.4

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm
