### ISSUE TITLE
Authenticators should fallback by default only if the required authentication data is not present in the request

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#29]
As of today, if you configure a rule to have multiple authenticators, the pipeline implementation always falls back to the next one if the previous fails. E.g.

```yaml
...
execute:
  - authenticator: a
  - authenticator: b
  - authenticator: c
```

So if "a" fails (regardless the reason), "b" is executed etc. This fallback should however by default only happen if the authentication data, like a specific cookie, or header, etc is not present in the request, but not when the actual verification of that data fails.
