### ISSUE TITLE
Documentation for `header` and `cookie` unifier are wrong

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#623]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Describe the bug

The documentation sais, the `header` unifier configuration looks as follows:
```yaml
id: foo
type: header
config:
  headers:
    - X-User-ID: {{ quote .Subject.ID }}
    - X-User-Email: {{ quote .Subject.Attributes["email"] }}
```

but the headers property is a map, so the proper configuration would be
```yaml
id: foo
type: header
config:
  headers:
    # note the absence of "-"
    X-User-ID: {{ quote .Subject.ID }}
    X-User-Email: {{ quote .Subject.Attributes["email"] }}
```

Same issue applies to the documentation of the `cookie` unifier. In addition the example uses `header` as type and not `cookie`

### How can the bug be reproduced

Just take a look in the docs

### Version

v0.7.0-alpha

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None
