### ISSUE TITLE
Enable access to the `Request` object in unifiers

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#624]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I have discussed this feature request with the community.

### Describe the background of your feature request

In some use cases heimdall is used to verify the validity of the authentication data only (e.g. during a migration from one IDP to another, or during the introduction of heimdall). In such cases the upstream service expects the original authentication data. In principle that can be achieved by having a rule with the following pipeline configuration:

```yaml
# this authenticator will verify the jwt
- authenticator: jwt
# do not create any headers or cookies to be forwarded to the upstream
- unifier: noop
```

The challenge with such setup is that, depending on the proxy used for the integration with heimdall, the proxy might strip the original authentication data (like jwt) and not forward it to the upstream. In addition, if multiple rules in heimdall side are used, with some which let heimdall set headers/cookies for the upstream and the other (like shown above) not, there is no way to let the proxy know, what to do in which case.

### Describe your idea

Let unifiers have access to the `Request` object. This way one can let heimdall setting the original headers with authentication data without having any issues or ambiguities on the proxy side.

Example:

```yaml
# this authenticator will verify the jwt
- authenticator: jwt
# set the original jwt to be forwarded to the upstream by the proxy
- unifier: forward
  config:
    headers:
      Authorization: '{{ .Request.Header "Authorization" }}'
```

### Are there any workarounds or alternatives?

Unfortunately no.

### Version

v0.7.0-alpha
