### ISSUE TITLE
Extend `jwt` unifier to allow definition of custom header and scheme

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#663]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I have discussed this feature request with the community.

### Describe the background of your feature request

As of today the `jwt` unifier creates a JWT and puts it into the `Authorization` header with `Bearer` scheme. Even it implements the typically expected scenario, there are systems out there, which expect other header names, as well as schemes. Especially, if migration to heimdall is considered.

### Describe your idea

Extend the configuration of the `jwt` unifier to allow definition of the header and the scheme. E.g.

```yaml
unifiers:
  - id: jwt
    type: jwt
    config:
      ttl: 5m
      header:
        name: Authorization
        scheme: Bearer
      claims: |
        {"user": {{ quote .Subject.ID }} }
```

with `header` being a new optional property, allowing to change the header name and scheme. If not set, it would result in the current behavior - `Authorization: Bearer <jwt value>` header set.

### Are there any workarounds or alternatives?

No

### Version

v0.7.0-alpha
