### ISSUE TITLE
Add support for capturing parts of the URL for use in the pipeline

### ISSUE THREAD

**Issue by netthier** [dadrus/heimdall#687]
NOTE: The problem described is already solvable, [see this comment](https://github.com/dadrus/heimdall/issues/687#issuecomment-1599382334).

### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I have discussed this feature request with the community.

### Describe the background of your feature request

Let's say I have a file API where users can access files via `/api/files/<uuid>`, where `<uuid>` refers to a specific file.
Not all users have access to all files, and whether a user has access or not should be checked by an authorizer accepting a payload such as
```yaml
- authorizer: openfga
  payload: |
    {
      "user": "user:{{ .Subject.ID }}",
      "relation": "read",
      "object": "file:<uuid>"
    }
```
As discussed [on Discord](https://discord.com/channels/1100447190796742698/1120442688806854697), it seems to currently not be possible to extract the `<uuid>` path segment from the URL.

### Describe your idea

This issue could be approached by making captured parts of the URL available in the pipeline context.
E.g. a rule for the aforementioned file API could look like this:
```yaml
id: foo
match:
  url: https://server/api/files/<.*>
  strategy: regex
execute:
  - authorizer: openfga
    payload: |
      {
        "user": "user:{{ .Subject.ID }}",
        "relation": "read",
        "object": "file:{{ index .Request.URL.CaptureGroups 0 }}"
      }
````
Where `.Request.URL.CaptureGroups` would theoretically contain an array of captured strings from the URL.

### Are there any workarounds or alternatives?

I'm not sure if there are any good alternatives to this except maybe polyfilling via a contextualizer.

### Version

n/a
