### ISSUE TITLE
heimdall panics with nil pointer dereference if called and there are no rules (incl default rule) available

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#698]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Describe the bug

If heimdall is configured without a default rule and there are no rules loaded (not configured, or included errors, so were not loaded), a request to heimdall results in a 500 error.

The expected behavior is heimdall not to panic and returning a 404 as described in the documentation.

### How can the bug be reproduced

1. Use the docker-compose setup e.g. using the proxy mode as starting point
2. Create an empty directory under the docker compose quickstarts directory
3. Update the heimdall configuration to not contain a default rule (comment them out)
4. Update the heimdall configuration to load the rules from a directory and not from a specific file
5. Change the `docker-compose.yaml` file to mount the directory from step 2 instead of the rule file and be mounted under the path specified in step 4.
6. Start the docker compose setup
    `docker-compose -f docker-compose.yaml -f docker-compose-proxy.yaml up`
7. Send a request to `curl -v http://127.0.0.1:9090/anonymous`. The answer will be 500

### Relevant log output

```shell
quickstarts-heimdall-1  | 2023-06-21T10:56:25Z DBG Proxy endpoint called _span_id=951790e255c0b1c8 _trace_id=33161ed4af22e818b481bf740b5ab740
quickstarts-heimdall-1  | panic: runtime error: invalid memory address or nil pointer dereference
quickstarts-heimdall-1  | goroutine 92 [running]:
quickstarts-heimdall-1  | runtime/debug.Stack()
quickstarts-heimdall-1  | 	runtime/debug/stack.go:24 +0x65
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2/middleware/recover.defaultStackTraceHandler(0x2801de9?, {0x2446ea0, 0x424c2f0})
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/middleware/recover/recover.go:12 +0x27
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2/middleware/recover.New.func1.1()
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/middleware/recover/recover.go:31 +0x7a
quickstarts-heimdall-1  | panic({0x2446ea0, 0x424c2f0})
quickstarts-heimdall-1  | 	runtime/panic.go:884 +0x213
quickstarts-heimdall-1  | github.com/dadrus/heimdall/internal/rules.(*ruleImpl).MatchesMethod(0xc0010ff8c0?, {0xc00152c058, 0x3})
quickstarts-heimdall-1  | 	github.com/dadrus/heimdall/internal/rules/rule_impl.go:81 +0x22
quickstarts-heimdall-1  | github.com/dadrus/heimdall/internal/handler/proxy.(*Handler).proxy(0xc00150cc30, 0xc00014b600)
quickstarts-heimdall-1  | 	github.com/dadrus/heimdall/internal/handler/proxy/handler.go:80 +0xf5
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc001038ae0?)
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/ctx.go:910 +0x43
quickstarts-heimdall-1  | github.com/dadrus/heimdall/internal/fiber/middleware/xfmphu.New.func1(0xc00014b600)
quickstarts-heimdall-1  | 	github.com/dadrus/heimdall/internal/fiber/middleware/xfmphu/handler.go:43 +0xf0
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2.(*App).next(0xc0014fc000, 0xc00014b600)
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/router.go:144 +0x1bf
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc001038600?)
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/ctx.go:913 +0x53
quickstarts-heimdall-1  | github.com/dadrus/heimdall/internal/fiber/middleware/proxyheader.New.func1(0xc00014b600)
quickstarts-heimdall-1  | 	github.com/dadrus/heimdall/internal/fiber/middleware/proxyheader/proxy_header.go:72 +0x3dc
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc001038ae0?)
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/ctx.go:910 +0x43
quickstarts-heimdall-1  | github.com/dadrus/heimdall/internal/fiber/middleware/cache.New.func1(0xc00014b600)
quickstarts-heimdall-1  | 	github.com/dadrus/heimdall/internal/fiber/middleware/cache/cache.go:29 +0x89
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2.(*Ctx).Next(0x26369e0?)
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/ctx.go:910 +0x43
quickstarts-heimdall-1  | github.com/dadrus/heimdall/internal/fiber/middleware/errorhandler.(*handler).handle(0xc001457a40, 0x0?)
quickstarts-heimdall-1  | 	github.com/dadrus/heimdall/internal/fiber/middleware/errorhandler/error_handler.go:46 +0x2a
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc001038ae0?)
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/ctx.go:910 +0x43
quickstarts-heimdall-1  | github.com/dadrus/heimdall/internal/fiber/middleware/logger.New.func1(0xc00014b600)
quickstarts-heimdall-1  | 	github.com/dadrus/heimdall/internal/fiber/middleware/logger/logger_handler.go:34 +0x2d3
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0013d75c0?)
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/ctx.go:910 +0x43
quickstarts-heimdall-1  | github.com/dadrus/heimdall/internal/fiber/middleware/accesslog.New.func1(0xc00014b600)
quickstarts-heimdall-1  | 	github.com/dadrus/heimdall/internal/fiber/middleware/accesslog/accesslog_handler.go:59 +0xa6c
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc11cd3b64bf38ac0?)
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/ctx.go:910 +0x43
quickstarts-heimdall-1  | github.com/dadrus/heimdall/internal/fiber/middleware/prometheus.(*metricsHandler).observeRequest(0xc001478740, 0xc00014b600)
quickstarts-heimdall-1  | 	github.com/dadrus/heimdall/internal/fiber/middleware/prometheus/handler.go:101 +0x2c9
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2.(*Ctx).Next(0xc00012c258?)
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/ctx.go:910 +0x43
quickstarts-heimdall-1  | github.com/dadrus/heimdall/internal/fiber/middleware/opentelemetry.(*tracer).manageSpans(0xc00012c258, 0xc00014b600)
quickstarts-heimdall-1  | 	github.com/dadrus/heimdall/internal/fiber/middleware/opentelemetry/tracer.go:76 +0x145
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2.(*Ctx).Next(0xa?)
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/ctx.go:910 +0x43
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2/middleware/recover.New.func1(0x241a500?)
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/middleware/recover/recover.go:43 +0xcb
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2.(*App).next(0xc0014fc000, 0xc00014b600)
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/router.go:144 +0x1bf
quickstarts-heimdall-1  | github.com/gofiber/fiber/v2.(*App).handler(0xc0014fc000, 0x4d5157?)
quickstarts-heimdall-1  | 	github.com/gofiber/fiber/v2@v2.46.0/router.go:171 +0x87
quickstarts-heimdall-1  | github.com/valyala/fasthttp.(*Server).serveConn(0xc0013eb200, {0x2dd5350?, 0xc00012c728})
quickstarts-heimdall-1  | 	github.com/valyala/fasthttp@v1.47.0/server.go:2365 +0x11d3
quickstarts-heimdall-1  | github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000758000, 0xc001478f00)
quickstarts-heimdall-1  | 	github.com/valyala/fasthttp@v1.47.0/workerpool.go:224 +0xa9
quickstarts-heimdall-1  | github.com/valyala/fasthttp.(*workerPool).getCh.func1()
quickstarts-heimdall-1  | 	github.com/valyala/fasthttp@v1.47.0/workerpool.go:196 +0x38
quickstarts-heimdall-1  | created by github.com/valyala/fasthttp.(*workerPool).getCh
quickstarts-heimdall-1  | 	github.com/valyala/fasthttp@v1.47.0/workerpool.go:195 +0x1b0
quickstarts-heimdall-1  |
```

### Relevant configuration

```yml
# docker-compose.yaml
version: '3.7'

services:
  heimdall:
    image: dadrus/heimdall:latest
    volumes:
      - ./heimdall-config.yaml:/heimdall/conf/heimdall.yaml:ro
      - ./empty:/heimdall/conf/rules:ro
    command: -c /heimdall/conf/heimdall.yaml serve decision

  upstream:
    image: containous/whoami:latest
    labels:
      - traefik.enable=true
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.http.routers.whoami.rule=PathPrefix("/")
      - traefik.http.routers.whoami.middlewares=heimdall

# heimdall.yaml
log:
  level: info

serve:
  decision:
    trusted_proxies:
      - 0.0.0.0/0

rules:
  mechanisms:
    authenticators:
      - id: do_nothing
        type: noop
      - id: anon
        type: anonymous
      - id: reject_requests
        type: unauthorized
    unifiers:
      - id: do_nothing
        type: noop
      - id: create_jwt
        type: jwt
    error_handlers:
      - id: default
        type: default
      - id: redirect_to_login
        type: redirect
        config:
          to: http://127.0.0.1:8080/login?origin={{ .Request.URL | urlenc }}
          when:
            - error:
                - type: authentication_error
                  raised_by: reject_requests
              request_headers:
                Accept:
                  - Bar

  providers:
    file_system:
      src: /heimdall/conf/rules
      watch: true
```

### Version

v0.8.1-alpha

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose
