### ISSUE TITLE
URL path is urlencoded twice when used to forward the request to the upstream in proxy mode

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#715]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Describe the bug

When a request with urlencoded path fragments (e.g. `http://127.0.0.1:9090/v1/%5Bid%5D/page`) is processed by heimdall operated in proxy mode, the path is urlencoded twice when the request is forwarded to the upstream. So, the URL from the example in braces used to forward the request looks `http://127.0.0.1:9090/v1/%255Bid%255D/page`

### How can the bug be reproduced

1. Use the docker-compose quickstart for proxy mode.
2. Adjust e.g. the second rule to match `http://<**>/v1/<**>`
3. Start the docker compose environment: 
    ```
    $ docker-compose -f docker-compose.yaml -f docker-compose-proxy.yaml up
    ```
4. Send a request using curl:
    ```
    $ curl -v http://127.0.0.1:9090/v1/%5Bid%5D/page
    ```

### Relevant log output

```shell
There is no need to look into the logs, the echo service used in the quickstart guide will echo everything received back. So, for the curl request from above, you'll see:

*   Trying 127.0.0.1:9090...
* Connected to 127.0.0.1 (127.0.0.1) port 9090 (#0)
> GET /anon/%5Bid%5D/page.js HTTP/1.1
> Host: 127.0.0.1:9090
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sat, 24 Jun 2023 14:56:30 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 746
< 
Hostname: 8eb90b3c2c0a
IP: 127.0.0.1
IP: 172.18.0.2
RemoteAddr: 172.18.0.3:47046
GET /v1/%255Bid%255D/page HTTP/1.1
Host: upstream:80
User-Agent: curl/7.88.1
Accept: */*
Authorization: Bearer eyJhbGciOiJFUzM4NCIsImtpZCI6ImVlMjViZDZkMjBjNGJiOWVmODU1ZTZjNzJmYjJkNWI1M2I0M2I4OGUiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE2ODc2MTg4MjMsImlhdCI6MTY4NzYxODUyMywiaXNzIjoiaGVpbWRhbGwiLCJqdGkiOiJhZmJmYmI5Mi1hYmZkLTRkYWUtODIzMC0yNGJjZWVhMzNlZjUiLCJuYmYiOjE2ODc2MTg1MjMsInN1YiI6ImFub255bW91cyJ9.5CeX8-t_Mo2p3GL3iykyFMcrC4UQwrVPmn6HYv9XtVlQKa688D2klZ_jGxwAumaSxO3AUkJfRgAMn8KopcTyayjTiBvKdXRGF7oNfAa1RXTXjmkorJbsG7mroe547Dew
Forwarded: for=172.18.0.1;proto=http
Traceparent: 00-a5984d561d8c535a0744b5a5eeb4dcf9-738af34a955317c7-01
X-Forwarded-For: 172.18.0.1

The relevant part from above is the following statement:
GET /v1/%255Bid%255D/page HTTP/1.1
```

### Relevant configuration

```yml
# upstream-rules.yaml from the quickstart guide
version: "1"

rules:
- id: rule1
  match:
    url: http://<**>/public
  upstream: http://upstream:80
  execute:
    - authenticator: do_nothing
    - unifier: do_nothing

- id: rule2
  match:
    url: http://<**>/v1/<**>
  upstream: http://upstream:80
  execute:
    - authenticator: anon
```

### Version

v0.9.0-alpha

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

### Additional Context

Related discussion in discord: https://discord.com/channels/1100447190796742698/1100447191358787646/1121841034121449472
