### ISSUE TITLE
The documentation doesn't say that simplifications available in the config file are not possible when using env variables

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#770]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."

### Describe the issue

As of today, there are some configuration options, which can be configured using a structured object or as just a string. Best example is the configuration of any endpoint. Here some examples:

```yaml
id: kratos_session_cookie
type: generic
config:
  identity_info_endpoint: http://foo.bar
```

The above is a simplified version of the following config

```yaml
id: kratos_session_cookie
type: generic
config:
  identity_info_endpoint: 
    url: http://foo.bar
```

While `..._CONFIG_IDENTITY__INFO__ENDPOINT_URL=http://foo.bar` is a valid configuration using env variables, the `..._CONFIG_IDENTITY__INFO__ENDPOINT=http://foo.bar` (no _URL at the end) is not valid and will be silently ignored.

### Version

v0.10.1-alpha

### Additional Context

Detected during analysis of https://github.com/dadrus/heimdall/issues/769
