### ISSUE TITLE
Support for HTTP method placeholders

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#773]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I have discussed this feature request with the community.

### Describe the background of your feature request

As of today, every HTTP method which should be allowed must be listed in the method property of a rule. This can make a rule pretty verbose, as shown below.

```yaml
- id: "nextjs:public"
  match:
    url: "http://localhost:5000<**>"
  forward_to:
    host: host.docker.internal:3000
    rewrite:
      scheme: http
  methods:
    - HEAD
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  execute:
    - authenticator: noop
    - authorizer: allow_all_requests
    - unifier: noop
```

As more rules are there as more verbose the corresponding rule sets will become.

### Describe your idea

It might be useful to have a shortcut/placeholder for that. So instead of listing all methods, something like ALL, or * could be used. So, the contents of the method property as shown above would be reduced to 

```yaml
methods:
  - ALL
```

Beyond that it might be beneficial to be able expressing something like "all methods, but OPTIONS". In principle, this could be achieved using something like:

```yaml
methods:
  - ALL
  - "!OPTIONS"
```

### Are there any workarounds or alternatives?

No

### Version

v0.10.1-alpha

### Additional Context

Link to the Discussion, respectively documentation of the idea in Discord: https://discord.com/channels/1100447190796742698/1121914132841635910/1121914132841635910
