### ISSUE TITLE
Enable fallback of Authenticators even if the verification of the given credentials fails

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#92]
As of today fallback of authenticators works only if the pipeline configures authenticators which expect different credentials as input. E.g. if one authenticator expects a cookie and the other one an access token. If however different authenticators expect same credential input. E.g. they are expecting an an access token in the `Authorization` header, fallback doesn't work.

Such fallback is however required if different Auth Providers are used to protect same resource. E.g. the system is configured to work with something like "Login with Google" and "Login with GitHub".

In principle the configuration can be done in a rule already today with something like this:

```yaml
execute:
 - authenticator: verify_google_token
 - authenticator: verify_github_token
```

The problem with the above example is however, that if the login has been done with GitHub, the `verify_github_token` authenticator will never be executed, as the `verify_google_token` authenticator will be executed first (according to the sequence above) and fail to verify the token, leading to an authentication error for the entire pipeline.

This can be enabled by introducing a specific configuration property for the authenticators, e.g.: `allow_fallback_on_error`, which would allow the pipeline to fallback to the next configured authenticator even the previous one failed. So the above pipeline configuration would become

```yaml
execute:
 - authenticator: verify_google_token
   config:
     allow_fallback_on_error: true
 - authenticator: verify_github_token
```

**Potential Workaround Today:** If there is a chance to configure the used Auth Providers to set the credentials into different fields, fallback works. This is always possible for cookies, as these are usually named provider specifically. This might be however problematic for providers issuing Auth2/OIDC tokens. As these are usually put into the `Authorization` header.
