### ISSUE TITLE
HTTP method expansion with placeholder key words in kubernetes RuleSet resources does not work

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#991]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I could not find a solution in the existing issues, docs, nor discussions.

### Describe the bug

Since the [v0.11.0-alpha](https://github.com/dadrus/heimdall/releases/tag/v0.11.0-alpha) release, there is an option to use placeholders for HTTP verbs to simplify the rules (implemented in #774). E.g.

```yaml
methods:
  - ALL
  - "!OPTIONS"
```

This does however not work with kubernetes RuleSet resources, as the corresponding CRD does not allow that as the schema in the CRD is defined as follows:

```yaml
methods:
  description: The allowed HTTP methods
  type: array
  items:
    type: string
    enum:
      - CONNECT
      - DELETE
      - GET
      - HEAD
      - OPTIONS
      - PATCH
      - POST
      - PUT
      - TRACE
```

### How can the bug be reproduced

Just create a RuleSet custom resource for an existing configuration with a `method` value set e.g. to `ALL`. The resource will be refused by the API server.

### Version

v0.11.1-alpha

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes
